<?php /* @var $this \Zend\View\Renderer\PhpRenderer */ ?>

<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Dlayer: Web Development Simplified')->setSeparator(' - ')->setAutoEscape(false); ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>

        <?php echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/x-icon', 'href' => $this->basePath() . '/images/favicon.ico'])
            ->headLink(['rel' => 'shortcut icon', 'sizes' => '192x192', 'href' => $this->basePath() . '/images/favicon-192x192.png'])
            ->prependStylesheet($this->basePath('bower_components/bootstrap/dist/css/bootstrap-theme.css'))
            ->prependStylesheet($this->basePath('bower_components/bootstrap/dist/css/bootstrap.css'));
        ?>

        <?php echo $this->headScript()
            ->prependFile($this->basePath('bower_components/bootstrap/dist/js/bootstrap.js'))
            ->prependFile($this->basePath('bower_components/jquery/dist/jquery.js'));
        ?>
    </head>
    <body>
        <nav class="navbar navbar-inverse" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home'); ?>">
                        <img src="<?php echo $this->basePath('images/brand.jpg'); ?>" width="25" height="25" alt="Dlayer" />
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="<?php echo $this->url('home'); ?>">Dlayer</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
        </div>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>


