<?php /* @var $this \Zend\View\Renderer\PhpRenderer */ ?>

<div class="row">
    <div class="col-md-12">
        <div class="jumbotron">
            <h1>Dlayer.com: <small>Web Development Simplified</small></h1>

            <p>Dlayer is an Open Source responsive web development tool aimed primarily at users with limited web design or development experience.</p>

            <p><a class="btn btn-primary btn-lg" href="http://www.dlayer.com" role="button">Learn more</a></p>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12">
        <p>[Login form here]</p>

        <p>[Show test credentials here]</p>
    </div>

    <div class="col-md-6 col-sm-6 col-xs-12">
        <h3><span class="label label-success">v2.xx</span> Latest version name <small class="text-muted">(Release date)</small></h3>

        <ul>
            <li>Changelog feature 1</li>
            <li>Changelog feature 2</li>
            <li>Changelog feature 3</li>
            <li>Changelog feature 4</li>
        </ul>

        <h3><span class="label label-default">v2.xx</span> Previous version <small class="text-muted">(Release date)</small></h3>
        <h3><span class="label label-default">v2.xx</span> Previous version <small class="text-muted">(Release date)</small></h3>
        <h3><span class="label label-default">v2.xx</span> Previous version <small class="text-muted">(Release date)</small></h3>
        <h3><span class="label label-default">v2.xx</span> Previous version <small class="text-muted">(Release date)</small></h3>
        <h3><span class="label label-default">v2.xx</span> Previous version <small class="text-muted">(Release date)</small></h3>

        <h3>And the older releases</h3>

        <p>The full <a href="http://www.dlayer.com/releases.html">release history</a> is available at Dlayer.com and
            on <a href="https://github.com/Dlayer/dlayer/releases">GitHub</a>.</p>
    </div>
</div>
